#!/usr/bin/env bash
SCRIPT_HOME_REL_PATH="${0%/*}"

if  [[ "${SCRIPT_HOME_REL_PATH}" != "." ]]; then
	APP_NAME=$(basename "${0}")
	echo "${APP_NAME}: For safety, this script must be run from the root project folder (same folder as the '${APP_NAME}' script itself)."
	exit 1
fi

if [[ ${#} -lt 1 ]] || [[ ${#} -gt 2 ]]; then
	APP_NAME=$(basename "${0}")
	echo "${APP_NAME}: Usage: ${APP_NAME} NewRustProject_name [-l]"
	echo "    Renames the project and the update CLion project files to reference NewRustProject_name."
	echo "    Optionally launches CLion, importing the renamed project if -l switch is present."
	echo "    This script commits changes to your git log, ensure git status is clean for best results."
	exit 1
fi

ORIG_PROJ_NAME=$(grep -Em 1 "name\s*=" Cargo.toml | sed -E "s/^name\s*=\s*\"(.*)\"$/\1/")

find . -not -iname "rename_project" -not -path "./.git" -not -path "./.git/*" -execdir rename "s/${ORIG_PROJ_NAME}/${1}/g" '{}' \+
find . -not -iname "rename_project" -not -path "./.git" -not -path "./.git/*" -type f -exec sed -Ei "s/${ORIG_PROJ_NAME}/${1}/g" "{}" \;

git >/dev/null commit -am "Renamed project to ${1}."

echo "Project renamed to ${1}. Remember to `git remote set-url origin repo_url:username/{$1}.git`, if applicable."
